### ISSUE TITLE
CSV encoding

### ISSUE THREAD

**Issue by rgieseke** [datasets/geoip2#2]
The CSV file appears to be encoded as ISO-8859-1, the [Tabular data spec](http://specs.frictionlessdata.io/tabular-data-package//#csv-files) asks for UTF-8. (I noticed this using reading it in with Pandas on Python 3, with `encoding="ISO-8859-1"` it works fine.)

**Comment by AcckiyGerman** [comment]
Yea, and that's why this datapackage could not be pushed to datahub:
`"UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 6348: invalid start byte”`

**Comment by Mikanebu** [comment]
FIXED, changed the encoding to `utf-8`. It is live now on http://datahub.io/core/geoip2-ipv4
