### ISSUE TITLE
Column names don't match the values

### ISSUE THREAD

**Issue by Penney3232** [datasets/geoip2#7]
Hi There, I'm using this CSV through PowerBI and yesterday noticed that my report broke and all the columns don't match the values now. Please can you look into this. 

For example...

network,geoname_id,continent_code,continent_name,country_iso_code,country_name,is_anonymous_proxy,is_satellite_provider
1.0.0.0/24,2077456.0,0,0,OC,Oceania,AU,Australia
![geoIPerror](https://github.com/user-attachments/assets/c908d235-f1ac-4875-80af-5b6dcefd55bf)

**Comment by gradedSystem** [comment]
Hi @Penney3232 I will look into this

**Comment by gradedSystem** [comment]
@Penney3232 Can you check the records now if they are columns and values are matching I just forgot to put one small detail which apparently changed the structure of the data, now should be fixed.

**Comment by gradedSystem** [comment]
I will close this issue for now, since user said it is fixed in the email, we can reopen this issue if it happens again
